# Arreglo de datos
## en este jupiter notebook nos encargaremos de reevisar los archivos de la carpeta "datos crudos" y convertirlos en un dataframe combeniente.

In [1]:
# importamos la libreria necesaria para la lectura
import pandas as pd

# nos situamos en la carpeta correspondiente
%cd "datos crudos"

c:\Users\Jose\Documents\GitHub\imt2200---actividad-2024\datos de indice de criminalidad\datos crudos

### Abrimos el archivo que contiene el indice de criminalidad por delito

In [54]:
df_ind_del = pd.read_excel("reportesEstadisticos-porDelito.xlsx", header=22)

df_ind_del.info()
df_ind_del

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 85 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DELITOS O FALTAS  4 non-null      object
 1   1                 4 non-null      object
 2   2                 4 non-null      object
 3   3                 4 non-null      object
 4   4                 4 non-null      object
 5   5                 4 non-null      object
 6   6                 4 non-null      object
 7   7                 4 non-null      object
 8   8                 4 non-null      object
 9   9                 4 non-null      object
 10  10                4 non-null      object
 11  11                4 non-null      object
 12  12                4 non-null      object
 13  1.1               4 non-null      object
 14  2.1               4 non-null      object
 15  3.1               4 non-null      object
 16  4.1               4 non-null      object
 17  5.1               4 non-null      object
 18  6.1               4 non-null      object
 19  7.1               4 non-null      object
 20  8.1               4 non-null      object
 21  9.1               4 non-null      object
 22  10.1              4 non-null      object
 23  11.1              4 non-null      object
 24  12.1              4 non-null      object
 25  1.2               4 non-null      object
 26  2.2               4 non-null      object
 27  3.2               4 non-null      object
 28  4.2               4 non-null      object
 29  5.2               4 non-null      object
 30  6.2               4 non-null      object
 31  7.2               4 non-null      object
 32  8.2               4 non-null      object
 33  9.2               4 non-null      object
 34  10.2              4 non-null      object
 35  11.2              4 non-null      object
 36  12.2              4 non-null      object
 37  1.3               4 non-null      object
 38  2.3               4 non-null      object
 39  3.3               4 non-null      object
 40  4.3               4 non-null      object
 41  5.3               4 non-null      object
 42  6.3               4 non-null      object
 43  7.3               4 non-null      object
 44  8.3               4 non-null      object
 45  9.3               4 non-null      object
 46  10.3              4 non-null      object
 47  11.3              4 non-null      object
 48  12.3              4 non-null      object
 49  1.4               4 non-null      object
 50  2.4               4 non-null      object
 51  3.4               4 non-null      object
 52  4.4               4 non-null      object
 53  5.4               4 non-null      object
 54  6.4               4 non-null      object
 55  7.4               4 non-null      object
 56  8.4               4 non-null      object
 57  9.4               4 non-null      object
 58  10.4              4 non-null      object
 59  11.4              4 non-null      object
 60  12.4              4 non-null      object
 61  1.5               4 non-null      object
 62  2.5               4 non-null      object
 63  3.5               4 non-null      object
 64  4.5               4 non-null      object
 65  5.5               4 non-null      object
 66  6.5               4 non-null      object
 67  7.5               4 non-null      object
 68  8.5               4 non-null      object
 69  9.5               4 non-null      object
 70  10.5              4 non-null      object
 71  11.5              4 non-null      object
 72  12.5              4 non-null      object
 73  1.6               4 non-null      object
 74  2.6               4 non-null      object
 75  3.6               4 non-null      object
 76  4.6               4 non-null      object
 77  5.6               4 non-null      object
 78  6.6               4 non-null      object
 79  7.6               4 non-null      object
 80  8.6               4 non-null      object
 81  9.6               4 non-null      object
 82  10.6              4 non-null      object
 83  11.6              4 non-null      object
 84  12.6              4 non-null      object
dtypes: object(85)
memory usage: 2.8+ KB

,DELITOS O FALTAS,1,2,3,4,5,6,7,8,9,...,3.6,4.6,5.6,6.6,7.6,8.6,9.6,10.6,11.6,12.6
0,Delitos violentos,"16.845,0000000000","14.828,0000000000","17.103,0000000000","16.469,0000000000","16.784,0000000000","15.514,0000000000","15.219,0000000000","16.754,0000000000","16.222,0000000000",...,"20.567,0000000000","19.062,0000000000","17.031,0000000000","16.717,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000"
1,Delitos asociados a drogas,"339,0000000000","288,0000000000","600,0000000000","606,0000000000","462,0000000000","388,0000000000","372,0000000000","383,0000000000","326,0000000000",...,"470,0000000000","515,0000000000","365,0000000000","342,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000"
2,Delitos asociados a armas,"349,0000000000","355,0000000000","662,0000000000","701,0000000000","686,0000000000","519,0000000000","588,0000000000","694,0000000000","648,0000000000",...,"522,0000000000","556,0000000000","893,0000000000","938,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000"
3,Delitos contra la propiedad no violentos,"12.332,0000000000","11.160,0000000000","13.099,0000000000","12.467,0000000000","13.102,0000000000","12.990,0000000000","12.990,0000000000","14.252,0000000000","12.252,0000000000",...,"9.414,0000000000","9.774,0000000000","10.151,0000000000","10.147,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000","0,0000000000"

In [53]:
# como mi formato siempre es de que las fechas se encuentren en las filas voy a invertir este dataframe
df_ind_del_inv = df_ind_del.T.reset_index(drop=True).iloc[1:-5]

# le cambiamos el nombre de las columnas de una forma muy original
df_ind_del_inv.columns = ["Delitos violentos", "Delitos asociados a drogas", "Delitos asociados a armas", "Delitos contra la propiedad no violentos"]

fechas = []
mes = 0
ano = 2018
for _ in range(len(list(df_ind_del.columns))):
    mes += 1
    if mes == 13:
        ano += 1
        mes = 0
    fecha = str(ano) + "-" + str(mes).zfill(2)
    fechas.append(fecha)

fechas = pd.DataFrame({"mes": fechas[:-1]})

df_ind_del = pd.merge(fechas, df_ind_del_inv, left_index=True, right_index=True)
df_ind_del

ValueError: Length mismatch: Expected axis has 84 elements, new values have 4 elements